#!/usr/bin/env bash
# configures nginx server to redirect to another page

sudo apt-get update
sudo apt-get install nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://intranet.alxswe.com/projects/266? permanent; }' /etc/nginx/sites-available/default

sudo service nginx restart
