#!/usr/bin/env bash
# returns an error code

sudo apt-get update
sudo apt-get install nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo mkdir /var/www/error
echo "Ceci n'est pas une page" > /var/www/error/404.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://intranet.alxswe.com/projects/266? permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default

sudo service nginx restart
