#!/usr/bin/env bash
#displays content of /etc/passwd

while IFS=: read -r username userid _ homedir _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo " Home directory: $homedir"
done < /etc/passwd
