#!/usr/bin/env bash
#this script displays best school 10 times

i=0
while ((i < 10)); do
	if ((i == 8)); then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
