#!/usr/bin/env bash
#displays time for 12hrs and 59 mins

hour=0
minutes=1

while ((hour <= 12)); do
    echo "Hour: $hour"
    while ((minutes < 60)); do
        echo "$minutes"
        ((minutes++))
    done
    ((hour++))
    minutes=1
done
