#!/usr/bin/env bash
# configures an ubuntu server changing home IP

if [ -e /etc/hosts ]; then
    sudo cp /etc/hosts /etc/hosts.old
    sudo sed -i 's/127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/g' /etc/hosts.old
    sudo sed -i 's/^8\.8\.8\.8.*$/8.8.8.8 facebook.com/g' /etc/hosts.old
    sudo cp -f /etc/hosts.old /etc/hosts
fi
